"""empty message

Revision ID: be8b51a57e36
Revises: ed4656c77ac0
Create Date: 2025-02-14 18:49:49.095403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8b51a57e36'
down_revision = 'ed4656c77ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('people_homeworld_key', type_='unique')
        batch_op.drop_constraint('people_name_key', type_='unique')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('people_name_key', ['name'])
        batch_op.create_unique_constraint('people_homeworld_key', ['homeworld'])
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')

    # ### end Alembic commands ###
